name: Release Tag

on:
  create:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    name: Package and Release
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: Install Node@latest
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install Deps
      run: npm ci
    - name: Package Files
      run: npm run package
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ddns-client.zip

